\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{multicol} % \begin{multicols}{number of columns} \end{multicols}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{Dissertation Notes}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle

%\setcounter{tocdepth}{3}  %%activate to number sections
%\tableofcontents

%\thispagestyle{empty}
%\setcounter{page}{0}
%\setcounter{secnumdepth}{-1}  %activate to start numbering from one
%on the second page
\section{Project List}
\begin{enumerate}
\item Simulation of ecological network evolution
  \begin{enumerate}
  \item When do interactions increase the community level genetic
    effects of a foundation species?
  \item IBM \url{http://www.railsback-grimm-abm-book.com/index.html}
  \end{enumerate}
\item Bark Lichen Co-occurrence
  \begin{enumerate}
  \item Enter data from last Spring
  \item Analyze data
  \item Write
  \end{enumerate}
\item Rock Lichen Co-occurrence
  \begin{enumerate}
  \item Need to incorporate analyses into SCRL1
  \item Analyze co-occurrence patterns for SCRL2
  \end{enumerate}
\item Arthropod Co-occurrence
  \begin{enumerate}
  \item Get data from leaves (senescing and litter)
  \item Enter data
  \item Analyze
  \end{enumerate}
\end{enumerate}

\section{6 Nov 2013}

Meeting with Tom:

\begin{itemize}
\item ACN
  \begin{itemize}
  \item Prelim results
  \item Binning species groups
  \item Tree traits
  \end{itemize}
\item Effective Community Diversity Chapter
  \begin{itemize}
  \item ???
  \end{itemize}
\item Dissertation
  \begin{itemize}
  \item Sign outstanding paperwork
  \item Committee meeting in January?
  \item Target to finish?
  \end{itemize}
\end{itemize}

\section{16 Oct 2013}

Meeting with Tom:

Think about research network.
\begin{itemize}
\item Aaron and the pitcher plants
\item Urban design and urban metabolism
\end{itemize}

\begin{enumerate}
\item Focusing on trait variation. What's Tom's suggestion?
  \begin{enumerate}
  \item "Phenotypic" trait variation
  \item Tie in with Sunset lit
  \item Fungal Ecology, Oecologia, Report for Ecology (genetics
    without genetics), Network Ecology?
  \item Look at bark traits from Barbour paper too
  \item Look for other bark roughess genetics papers
  \item 
  \end{enumerate}
\item Can you write a genetics paper without roughness?
\item Network perspective?
\end{enumerate}



From Tom's comments on the outline:
\begin{itemize}
\item Make results in abstract agree with presentation in body
\item Focus on trait variation effects and end with a conclusion that
  the genetic component should be investigated
\item Get the genetics for Goncho's trees and see where they fall out
  on Matt's hybrid index
\end{itemize}

\section{2 Oct 2013}

Meeting with Tom,

\begin{enumerate}
\item Wild stand, SES~roughness, P=0.0127
\item Art's manuscript
  \begin{itemize}
  \item Read through Art's manuscript
  \item See where networks fit
  \item Re-do network analyses, write-up methods, add results for Art
  \end{itemize}
\end{enumerate}

\section{25 Sep 2013}

\subsection{Meeting with Tom}

Discussed LCN project results (see github Issues)

\begin{enumerate}
\item Finish wild analyses
\item Start wild paper
\item Start garden analyses
\end{enumerate}

Email Adrian about arthropod networks paper.

\section{18 Sep 2013}

\subsection{Meeting with Tom}
\begin{itemize}
\item lco
\item 
  \begin{itemize}
  \item take home - interaction network structure is determined by the
    ecological variation created by roughness which is genetically
    based. 
    \begin{enumerate}
    \item roughness drives composition (cite lamit's work)
    \item co-occurrence at the tree level tracks roughness in the wild
      (c-score vs roughness)
    \item co-occurrence at the tree level tracks roughness in the
      garden (pit too?) (c-score vs roughness)
    \item interaction networks inferred from co-occurrence patterns
      similar in wild and garden (all positive patterns, two central
      species) (mantel test)
    \item interaction network structure tracks roughness (how to show this?)
    \end{enumerate}
  \end{itemize}
\item ecd
  \begin{itemize}
  \item need to understand the math before moving forward
  \item putting on a scale?
  \item simple three species networks?
  \item using lichen network as a real example?
  \end{itemize}
\end{itemize}


\section{2013 Aug 30}

Dissertation folder is now on git. Use the git_stage to work with it
for now.

Note: Consider the data storage limitations of github. For example,
huge data or image files would not be able to be stored there

Reorganizing projects to use git.

Use git for every day changes. Make notes of major changes in
notebooks for each project and keep track of dissertation projects as
a whole here. 

---Cottonwood Meeting Schedule---
Sept 6 – No presentation; Tom out of town
Sept 13 – Practice talks for Biennial Conference by Hillary Cooper,
Dana Ikeda, Kevin Grady, others?
Sept 20  - Todd Wojtowicz
Sept 27 – Art Keith - Interacting foundation species hypothesis: how
genetics-based interactions affect community diversity, stability and
network structure
Oct 4 – Gery Allan and Andy Krohn Andy - Next Generation Sequencing:
Ecological Applications
Oct 11- Dana Ikeda (virtual manuscript review-Fremont seedling
germination experiment)
Oct 18 – Scott Woolbright (virtual manuscript review – Quantitative
genetics of plant defenses or Community genetics of island relicts)
Oct 25 – Zacchaeus Compson
Nov 1 -  Matt Lau (virtual manuscript review – community genetics of
lichens)
Nov 8 -   Kimberly Whitley
Nov 15 -  Helen Bothwell - Population genetics of narrowleaf
cottonwood
Nov 22 – Kevin Grady - Long-term Riparian Monitoring Network -
collaborative potential, funding opportunities, and future needs
Nov 29 - Thanksgiving Holiday
Dec 6 - Lluvia Hilda Flores Renteria – Cosmic questions revolving
around pinyon genetics

\section{2013 Jul 03}
Initiated the "Network Evolution" project folder. 

This incorporated the files and information from "eco_genetic_information" and
"evolution_on_ecological_networks" folders. 

There is now a project notebook.

\section{2013 Jul 01}

(Life Long Activist \url{http://lifelongactivist.com/})

Manage your:

\begin{itemize}
\item Mission
\item Time
\item Fears
\item Relationship with Self
\item Relationship with Others
\end{itemize}

\textbf{Network Perspective for Evolution Ecological Communities}
\begin{itemize}
\item Interactions usually occur at the scale of the individual
\item Species are groups of individuals with similar traits/genetics 
\item Trophic networks can "evolve" through ecological and
  evolutionary processes
\item Species interaction networks can evolve through ecological shifts in
  individual behavior and turn-over in individuals from demographic
  shifts or immigration/emigration
\item Interactions are determined by a limited set of phenotypic
  traits
\item Ecological networks tend to have repeated structure
\item Indirect effects are important in ecological systems
\item Understanding interaction phenotypes will aid the understanding
  of GxE
\end{itemize}


\section{2013 Jun 28}
Project Ideas: Simulation of Evolution of Ecological Networks

\begin{itemize}
\item Crux: how networks of interacting species evolve is not well
  understood
\item What we need to know?
  \subitem We need an integrated framework of how evolution works in
  networks of interacting species
  \subitem We also need to test how different factors can influence
  the evolution of network structure
\item What we do we already know?
  \begin{itemize}
  \item Ecological genetics = the heredity of traits that determine
    the distribution and abundance of organisms
  \item Ecology can influence evolution via mutation, drift, migration
    and natural selection
  \item Only natural selection leads to adaptation, others only affect
    the rate of adapation
  \item Studies of ecological networks show structural signatures of
    selection (e.g. nestedness)
  \end{itemize}
\item What do we need to do?
  \subitem Simulation Overview
  \begin{enumerate}
  \item Define species traits 
  \item Define genetic structure
  \item Generate populations
  \item Create ecological scenario
  \item Track genetics and ecology
  \end{enumerate}
\item What resources do we have?
  \begin{itemize}
  \item Lonsdorf's MatLab code
  \item Andrea Sala's manuscript and code
  \item See Miguel's recent paper on artificial life
  \item Allesina lab simulations
  \item Amazon Web Server
  \item EcoBeaker
  \item NetLogo
  \item enaR
  \item foreach: simple paralellization
  \end{itemize}
\end{itemize}

\begin{verbatim}

  ---------------------------------------> Ecological factors (=selective agents)
  |                                                Biotic      Abiotic
  |                                            *interactions*    |    
  |                                                    |         |
  |                                                    V         V
  |   Mutation            Genetic variation        Observed differences 
  |   recombination ----> in traits related         among phenos. = 
  |                       to fitness       \        / natural selection
  |                              ^          \______/  
  |                              |              |
  |                               \             V
  |                                 Genetic composition
 Mean phenotype <-----------------  of population
                                    (allele freqs.)
                                      ^         ^    
                                      |         |    
                                     /           \  
            *Establishment* ---> Migration    Genetic Drift <--- *Pop. Size*
                  ^                                                                     
                  |______*from Ecological Factors*


Figure 1.1 in Connor and Hartl. Map of the four evolutionary processes
and their ecological links, some added by me*.

\end{verbatim}

Notes on information and ascendency in evolution

%%%Entropy = Indeterminacy = H = -sum(p*log(p)) for all N
%%%Hmax = log(N)
%%%Information = Hmax - H, where the assumer reference state for information is maximum entropy

%% evo-nets 
%% - previous studies look at diversity loss with species removal and treat species as phenotypically static
%% - understanding how species and whole networks will evolve is key to understanding and predicting ecosystem dynamics 
%% - this project will use theoretical and empirical networks to explore the evolutionary impacts of species losses in networks
%% - this has broad implications beyond ecology and evolutionary biology to networks with nodes comprised of similar but varying individuals


\section{2013 Jun 27}
Matie \url{http://cran.r-project.org/web/packages/matie/matie.pdf}:
looks for assciations using likelihood based method.

\subsection{How to finish your dissertation. (Hillary Rettig)}

Writing Tips from
\url{http://www.howtofinishmythesis.com/writing-tips/how-to-finally-finish-your-book-or-thesis/}

\begin{itemize}
\item Isolation and Invisibility as Key Tactics and Goals of Procrastination
  \begin{itemize}
  \item Procrastination can derive from a desire to not be seen and
    can drive underacheivement.
  \item Be sure to be seen. Don't hide. Be productive and make both
    your successes and failures public.
  \item It's OK to fail.
  \end{itemize}
\item How to Finally Finish Your Book
  \subitem Finish what you start
  \begin{enumerate}
  \item Choose the right project
  \item Set the right goal
  \item Forget your audience
  \item Work in Community and find a critique partner
  \item Write fast
  \item Expect problems
  \item Learn to write past the wall
  \item Strategies to get past blocks
  \item Deal with non-writing issues
  \item Ergonimics matters!
  \item Pay attention to your needs (intercept restlessness and
    fatigue early)
  \item Track and reward your progress
  \end{enumerate}
\item What to Do if You Have a Procrastination Problem or Block
  \begin{enumerate}
  \item Minimize causes of fear
  \item Build coping capacity and writing endurance
    \subitem Get a clock and time 5 minutes, then relax and restart
  \end{enumerate}
\item How to Use Speed to Overcome Writer’s Block
  \begin{enumerate}
  \item Be consistent. Don't write in fits and starts.
  \item Be zen.
    \begin{enumerate}
    \item Detach from the task to get over the fear of getting it done.
    \item Focus just on writing, avoid distractions (including Email!!!
      and looking things up)
    \item Simplify:
      \begin{enumerate}
      \item Assess the quality appropriate for the writing task
      \item What parts can you eliminate?
      \item How can you simplify the remaining parts?
      \item What resrouces do I have to help finish?
      \item Who can I enlist to help me?
      \end{enumerate}
    \end{enumerate}
  \item Share drafts and get feedback, recognize weak points
  \end{enumerate}
\item How to Find and Keep a Mentor
  \subitem Mentors are everywhere!
  \begin{enumerate}
  \item Start small (recognize time and commitment limitations)
  \item Always be professional
    \begin{enumerate}
    \item Stay on time
    \item Focus on problem solving (not how it's making you feel)
    \item Be thankful (send thank yous)
    \end{enumerate}
  \item Always ask the key question
  \item Stay in touch
    \begin{enumerate}
    \item Don't just contact when you need things
    \item Share relevant news
    \end{enumerate}
  \item Reciprocate
  \item Mentor!
  \end{enumerate}
\end{itemize}

\section{2013 Apr 29}
Memmott (2004) Tolerance of pollination networks to species
extinctions. PRSB:
\url{http://m.rspb.royalsocietypublishing.org/content/271/1557/2605.full.pdf}

Check out Nickolas Waser:
\url{http://www.biology.ucr.edu/people/faculty/Waserpubs/NWpubs.html}

Body Size and Ecological Networks:
\url{http://complex.upf.es/~montoya/TREE_Woodward_et_al_in_press.pdf}

Can you incorporate body size measurements into your dissertation? 

- genetic control of body size in cottonwoods?
- lichen body size?
- artrhopod body size?

Information Processing Networks
\begin{verbatim}

In information-processing networks, the motifs may have specific
functions as elemen- tary computational circuits (11). More general-
ly, they may be interpreted as structures that arise because of the
special constraints under which the network has evolved (27).
\end{verbatim}

Can you analyze life-history data to construct networks?
\url{http://cran.r-project.org/web/packages/Biograph/index.html}

Tim Keit Paper:
Productivity, nutrient imbalance and fragility in coupled
producer–decomposer systems
\url{http://www.sciencedirect.com/science/article/pii/S0304380012002414}

\section{2013 Apr 11}
Could you use a tournament style simulation?

\url{http://www.r-bloggers.com/tit-for-tat-axelrod-tournament-style-competitive-simulation/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+RBloggers+%28R+bloggers%29}

Articles from the Game Theory Lit:

\begin{itemize}
\item Axelrod and Bennet (1993) A landscape theory of
  aggregation. British Journal of Political Science. 23: 211-33.
\item Axelrod (1987) The evolution of strategies in the iterated
  prisoner's dilemma. In Genetic Algorithms and Simulated Annealing,
  ed. Lawrence Davis. 
\end{itemize}

Big data techniques might be useful for visualizing simulations:

\url{http://www.r-bloggers.com/visualize-large-data-sets-with-the-bigvis-package/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+RBloggers+%28R+bloggers%29}


\section{2013 Apr 01}
These two papers should be useful for evolution of pollination networks.

Bradshaw 1995 Mimulus

Tolerance of pollination networks to species extinctions
Jane Memmott, Nickolas M. Waser and Mary V. Price

\section{2013 Mar 27}
\begin{verbatim}
"Try to learn something about everything and everything about
something." 
- Thomas Henry Huxley (1825-1895)
\end{verbatim}


\section{2013 Mar 15}
Pringle Lab Meeting
Discussion on scientific journalism
\begin{enumerate}
\item selling science
\item Cohn's law: new hope and no hope
\item data-mining for journalism
\item freelancing
\item tips for interviewing:
\item  metaphors
\item  explicitly state importance
\item  ask to re-phrase
\item  look for press releases
\item  Harvard Box Center communication courses
\end{enumerate}


\section{2013 Mar 13}
Axelrod's The Evolution of Cooperation may be useful for community
genetics simulations.

\url{http://www-personal.umich.edu/~axe/research/Software/ComplexCoop.html}

\section{2013 Mar 6}
\begin{verbatim}
Here’s why the journal is worthy of your attention: 

1) AoB PLANTS is owned by a non-profit organization that has over 100
years of experience publishing plant research;
2) The journal has distinguished Advisory and Editorial Boards
composed of scientists from around the world;
3) It has published influential and widely cited articles since its
establishment in 2009, with ~6,000 article downloads/month;
4) Submitted manuscripts are assessed rapidly using double-blind peer
review, aiming for first decisions in 30 days;
5) Papers are published online within days of acceptance;
6) Articles are published under the most widely-accepted form of
open-access license (CC-BY); and
7) The journal has one the lowest open-access fees for a journal in
the biological sciences, and they have been waived entirely for 2013. 

Here’s what people are saying about AoB PLANTS:
the long-term experience and reputation of Oxford University Press."
Osvaldo Sala - Julie A. Wrigley Chair & Foundation Professor, Arizona
State University

“With broad coverage of the plant sciences and an intensifying focus
on environmental biology, AoB PLANTS publishes articles of great
interest and embraces an open-access policy that ensures they are
widely read.”
Daniel Simberloff - Nancy Gore Hunger Professor of Environmental
Science, University of Tennessee; Editor-in-Chief, Biological
Invasions

AoB PLANTS has commissioned the following review articles for
publication in 2013:

Floral precision and speciation in flowering plants
Scott Armbruster (University of Portsmouth)

Early angiosperm evolution viewed through an ecophysiological prism
Taylor Feild (James Cook University)

Hitting the right target: taxonomic challenges of and for biological
invasions
Petr Pysek (Academy of Sciences of the Czech Republic), Philip
E. Hulme (Lincoln University), David M. Richardson (University of
Stellenbosch) and others

Phenological niches and the future of invaded ecosystems with climate
change
Elizabeth M. Wolkovich (University of British Columbia) and Elsa
[E. Cleland (University of California, San Diego)

Why find the genes for ecologically important traits?  A rationale for
the QTN program
Young Wha Lee, Billie A. Gould, John R. Stinchcombe (University of
Toronto)

If you are interested in ecological and evolutionary research with a
plant focus, please check out AoB PLANTS at
www.aobplants.oxfordjournals.org.

Many thanks,

Hall Cushman
Chief Editor, AoB PLANTS
\end{verbatim}

\section{2013 Feb 10}

Look into modeling phenology data: \url{http://cran.r-project.org/web/packages/phenology/index.html}

\section{2013 Feb 04}

Career Thoughts
\begin{itemize}
\item Primary Skill Set:
  \begin{itemize}
  \item Quantitative skills (stats, math, networks, modeling)
  \item Computer skills (R, python, bash, linux, unix, AWS, servers)
  \item Teaching skills (ecology, R)
  \end{itemize}
\item Possible Tracks:
  \begin{itemize}
  \item Big data in ecology (information)
  \item Ecological information theory (merging community genetics and ecosystem theory)
  \item The evolution of ecosystems and the control of information (as
    an ecosystem develops, how is information stored and how does it flow)
  \end{itemize}
\end{itemize}

Markov Chains as a model for community dynamics
\begin{itemize}
\item Transition probilities determined by interactions
\item In a 2 species community the transition matrix would be 2x2
\item In an n species community the maximum size of the transition matrix
  would the square of the number of unique combinations of n species
\item In reality the number of actual interactions that matter to the
  transition matrix is extremely small
\end{itemize}

%% %%Figure construction
%% <<echo=false,results=hide,label=fig1,include=false>>=
%% @ 


%% %%Figure plotting
%% \begin{figure} 
%% \begin{center} 
%% <<label=fig1,fig=TRUE,echo=false>>=
%% <<fig1>> 
%% @ 
%% \end{center} 
%% \caption{}
%% \label{fig:one}
%% \end{figure}


%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


