%%%NOTE: for help with latex symbols look here http://mirror.unl.edu/ctan/info/symbols/comprehensive/symbols-a4.pdf.
\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{multicol} % \begin{multicols}{number of columns} \end{multicols}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}


\title{Foundation species genetics structures lichen community
  interaction networks}
\author{M.K. Lau, L.J. Lamit, T.G. Whitham}
\begin{document}
\maketitle


\setcounter{tocdepth}{1}
\tableofcontents

\section{Analyses}

<<>>=
source('~/projects/dissertation/projects/onc_lichen/src/wild_stand.r')
source('~/projects/dissertation/projects/onc_lichen/src/onc.r')
source('~/projects/dissertation/projects/onc_lichen/src/pit.r')

@ 

\section{9 Oct 2013}

\textbf{Analysis Outline}
\begin{enumerate}
\item Resolve species
\item Stand Level SES and Araujo Net
\item Composition ~ Height
\item SES ~ Richness
\item SES ~ Abundance
\item Age ~ Roughness
\item SES ~ Roughness
\item SES ~ Age
\end{enumerate}



\section{2 Oct 2013}

Meeting with Tom, see dissertation/notebook.Rnw

\section{25 Sep 2013}

Meeting with Tom, see dissertation/notebook.Rnw

\textbf{Analytics Outline}

\begin{enumerate}
\item Look at the effect of height and tree (Can you lump upper and lower?)
\item Basic community responses to roughness
\item Stand level ecoSim analysis and Araujo modeling
\item Tree level ecoSim analysis and Araujo modeling
\item Trait network patterns?
\item Effective community diversity?
\item Information theoreitc patterns?
\end{enumerate}

\section{18 sep 2013}

continuing analyses from the 17 sep 2013. see chunk below.


\section{17 sep 2013}
\begin{itemize}
\item got wild stand data from lamit (= ``uintamaster_lichenheritnl_fallspring_2012_forlau.xls'')
  \subitem ``i excluded 2 trees, i think, because the cores were hard
  to read and i could not get a reliable age. one sheet is the raw
  data by quadrat and one is the final averaged data i used in the
  manuscript''
\item finished wild stand data (note: a check on the 45-55n = entered)
\item analyzed data:
\end{itemize}

\subsection{wild stand analysis}

\textbf{previous work}
\begin{itemize}
  \subitem richness, total cover, community composition
\item genotypes vary in development of rough bark
\item crustose and foliose respond differently 
\end{itemize}

\textbf{analysis summary}
\begin{itemize}
\item roughness affects the co-occurrence patterns of lichen in the field
\item roughness is geneticaly based
\item 
\end{itemize}




\section{16 sep 2013}

\begin{itemize}
\item re-organized files to conform with current best practices for
  projects
\item now on github
\item ecosimr doesn't have the co-occurrence analyses built in
\item began the final phase of data entry (adding to lco_apr2012.csv)
\end{itemize}



\end{document}


%%%%%old code
%%%%%moved out of document on 16 sep 2013
%%%%%pull out necessary analyses

%%%chunk0
<<echo=false,results=hide>>=
  ###turn off the permanova's
  ###make sure to turn this on when starting a new session in r.
  ###note! you turned off the permanova for genotype alone
  if (any(ls() == adonis.on)){}else{adonis.on <- true}

@ 

%%%chunk1
<<echo=false,results=hide>>=
  ##package dependencies
  library(xtable)
library(ecodist)
library(vegan)
library(gdata)
library(gplots)
library(sna)
library(lme4)
library(rlrsim)
library(fossil)
source('/users/aeolus/documents/active_projects/cornets/cornets.r')
source('/users/aeolus/documents/r_docs/scripts/functions/pairs.r')
source('~/documents/active_projects/new_functions/new_functions.r')
source('~/documents/inactive_projects/geneticnetworks/genetic_networks/ind_net.r')

@ 


%%%chunk2
<<echo=false,results=hide>>=
##load data

##onc
  lco <- read.csv('/users/aeolus/documents/active_projects/onc_lichen/onc_lco_data/onclichencooc_12may2011.csv')
##pit
                                        #lco <- read.csv('/users/aeolus/documents/active_projects/onc_lichen/onc_lco_data/pitlichencooccurrencemay2011.csv')


##remove genotypes
#lco <- lco[lco$geno != 't6',]
                                        #lco <- lco[lco$geno != 'rl6',]
#lco <- lco[lco$geno != 'h10',]
#lco <- lco[lco$geno != '999',]
#lco <- lco[lco$geno != '1007',]

##model networks for each quadrat
attach(lco)
names(lco)
tree.info <- paste(tree,geno,quadrat,year,sep='_') #integrate tree information
detach(lco)

##separate species observations
lco.com <- lco[,7:15]

@ 


%%%chunk3
<<echo=false,results=hide>>=
##model networks
lco.nets <- list() #initiate tree network object
lco.com.all <- list()

for (i in (1:length(unique(tree.info)))){
  lco.com.all[[i]] <- lco.com[tree.info == unique(tree.info)[i],]
  x <- kendall.pairs(lco.com[tree.info == unique(tree.info)[i],],p.adj=false)
  x[is.na(x)] <- 0#make na values zero
  lco.nets[[i]] <- x
}

names(lco.nets) <- unique(tree.info) #name networks
names(lco.com.all) <- unique(tree.info) #name com.all

##independence networks
inet <- list()
                                        #cut.off for species' observation frequencies
cut.off <- 3
                                        #loop through to generate network for all trees
for (i in 1:length(lco.com.all)){
  x <- lco.com.all[[i]]
  x <- x[,apply(x,2,sum) >= cut.off]
  if (class(x) == 'integer'){x <- matrix(x,ncol=1);colnames(x)[1] <- colnames(lco.com.all[[i]])[1]}
  if (length(apply(x,2,sum)[apply(x,2,sum) != 0]) <= 1){
    inet[[i]] <- array(0,dim=c(ncol(lco.com.all[[i]]),ncol(lco.com.all[[i]])))
    colnames(inet[[i]]) <- rownames(inet[[i]]) <- colnames(lco.com.all[[i]])
  }else{
    inet[[i]] <- ind.net(as.matrix(vegdist(t(x))),nrow(x),fix.na=true)
  }
}

conform.array <- array(0,dim=c(ncol(lco.com.all[[1]]),ncol(lco.com.all[[1]])))
colnames(conform.array) <- rownames(conform.array) <- colnames(lco.com.all[[1]])
inet <- lapply(inet,function(x) conform(x,conform.array)[[1]])

@ 

%%%chunk4
<<echo=false,results=hide>>=
##separate network factor information (tree, genotype, quadrat, year of sampling)
net.info <- unique(tree.info)
info.info <- rep(paste('tree','geno','quad','year',sep='_'),length(net.info))
tree.factor <- unlist(strsplit(net.info,split='_')) #tree-level information for each network
info.factor <- unlist(strsplit(info.info,split='_')) #sep information for tree information

net.tree <- tree.factor[info.factor == 'tree'] #tree number information for each network
net.geno <- tree.factor[info.factor == 'geno'] #genotype information for each network
net.quad <- tree.factor[info.factor == 'quad'] #quadrat information for each network
net.year <- tree.factor[info.factor == 'year'] #year of sampling for each network

@ 


%%%chunk5
<<echo=false,results=hide>>=
##import roughness data
rough <- read.csv('data/onc_raw_roughness.csv')
rough[is.na(rough)] <- 0 #replace na values with zeros
rough[rough == ' '] <- 0 #replace empty spots with zeros
rough <- rough[rough[,1] != '',] #remove empty/place holder rows
names(rough)[1] <- 'tree' #re-name the tree column
names(rough)[2] <- 'geno' #re-name the genotype column
names(rough)[3] <- 'quadrat' #re-name quadrat column
                                        #coerce the tree names
rough$tree <- as.character(rough$tree)
rough$tree <- as.mytree(rough$tree)
                                        #re-name quadrat locations
rough$quadrat <- as.character(rough$quadrat)
rough$quadrat[rough$quadrat == 'north 45-55'] <- 'n45.55' #north 45 - 55
rough$quadrat[rough$quadrat == 'north 80-90'] <- 'n80.90' #north 80 - 90
rough$quadrat[rough$quadrat == 'south 45-55'] <- 's45.55' #south 45 - 55
rough$quadrat[rough$quadrat == 'south 80-90'] <- 's80.90' #south 80 - 90

                                        #for each quadrat on each tree, separate the roughness information
names(rough)
attach(rough)
net.rough <- numeric()
rough.tq <- paste(tree,quadrat) #create a vector for coalescing the roughness data
net.tq <- paste(net.tree,net.quad)

for (i in (1:length(net.tq))){
  net.rough[i] <- roughness.[rough.tq == net.tq[i]]
}

detach(rough)

@ 


%%%chunk6
<<echo=false,results=hide>>=
##import tree position data
gps <- read.csv('data/nonc_gps_data.csv')[,1:3]
gps$location <- as.mytree(as.character(gps$location))
                                        #add missing trees
                                        #check with jamie to make sure these data are correct
gps <- rbind(gps,c('n1.5', -111.9995,  41.24699))
gps <- rbind(gps,c('n1.7', -111.9995, 41.24709))
gps <- rbind(gps,c('n2.31', -111.9995823, 41.248322))
gps <- rbind(gps,c('n1.24', -111.999534, 41.247919))

                                        #initiate the lat and log vectors for the network locations
net.lat <- numeric() #lat
net.lon <- numeric() #lon

for (i in (1:length(net.tree))){
  net.lat[i] <- gps$latitude[gps$location == net.tree[i]]
  net.lon[i] <- gps$longitude[gps$location == net.tree[i]]
}

                                        #coerce into numeric
net.lat <- as.numeric(net.lat)
net.lon <- as.numeric(net.lon)

##calculate species richness
net.rich <- numeric()
for (i in (1:length(unique(tree.info)))){
  x <- lco.com[tree.info == unique(tree.info)[i],]
  net.rich[i] <- sum(apply(x,2,function(x) if (any(x) > 0){1}else{0}))
}

@ 

%%%chunk7
<<echo=false,results=hide>>=
##permanova for networks
net.dist <- as.dist(netdist(lco.nets)) #calculate the network distances
inet.dist <- as.dist(netdist(inet))

                                        #is space an important co-variate?
                                        #probably not.
geo.dist <- earth.dist(cbind(net.lon,net.lat))
#mantel(geo.dist~net.dist)
###mantel of community, network and geo distances


@ 



%%%chunk8
<<echo=false,results=hide>>=
                                        #what about analyzing the quadrats separately?
                                        #yes, when we remove t6.
net.dist45 <- netdist(lco.nets[net.quad == 'n45.55'])
inet.d45 <- netdist(inet[net.quad == 'n45.55'])
net.geno45 <- net.geno[net.quad == 'n45.55']
net.rough45 <- net.rough[net.quad == 'n45.55']
net.lon45 <- net.lon[net.quad == 'n45.55']
net.lat45 <- net.lat[net.quad == 'n45.55']
#adonis(net.dist45~net.geno45)
#adonis(net.dist45~net.geno45*net.rough45)
#adonis(net.dist45~net.geno45*net.lon45,permutations=9999)
genotype <- factor(net.geno45)
longitude <- net.lon45
#if (adonis.on == true){adonis.genoxlon <- adonis(net.dist45~genotype*longitude,permutations=9999)}

@ 


%%%chunk9
<<echo=false,results=hide>>=
##analyze structural statistics

##only using the lower quadrats
lco.nets45 <- lco.nets[net.quad == 'n45.55']


##degree
net.l45 <- unlist(lapply(lco.nets45,function(x) length(x[x!=0])/2)) #undirected, so only count one link per pair
#plot(net.l45~factor(net.geno45))
#summary(aov(net.l45~net.geno45*net.lon45))

##size (i.e. number of nodes)
net.s45 <- unlist(lapply(lco.nets45,netsize))
#plot(net.s45~factor(net.geno45))
#plot(net.l45~net.s45)
#summary(aov(net.s45~net.geno45*net.lon45))

##centralization
net.c45 <- unlist(lapply(lco.nets45,function(x) centralization(x,degree,mode='undirected')))

#hist(net.c45)
#hist(sqrt(asin(net.c45)))
#plot(net.c45~factor(net.geno45))
#summary(aov(sqrt(asin(net.c45))~net.geno45*net.lon45))


##correlations with richness
net.rich45 <- net.rich[net.quad == 'n45.55']
genotype <- factor(net.geno45)
longitude <- net.lon45
aov.rich.genoxlon <- summary(aov(net.rich45~genotype*longitude))

#summary(aov(net.rich45~net.geno45*net.rough45))
#summary(aov(net.rich45~net.geno45*net.rough45))
#summary(aov(net.rich45~net.lat45))
#pairs(cbind(net.rich45,net.s45,net.l45,net.c45),pch=19)

##whole model:
richness <- net.rich45
size <- net.s45
degree <- net.l45
centralization <- net.c45

if (adonis.on == true){adonis.genoxrich <- adonis(inet.d45~genotype*richness,permutations=9999)}
aov.s45.genoxrich <- summary(aov(net.s45~genotype*richness))
aov.l45.genoxrich <- summary(aov(sqrt(net.l45)~genotype*richness))
aov.c45.genoxrich <- summary(aov(sqrt(asin(net.c45))~genotype*richness))
if (adonis.on == true){adonis.netd.all <- adonis(inet.d45~richness+size+degree+centralization,permutations=9999)}

@ 



%%%chunk10
<<echo=false,results=hide,label=gplots,include=false>>=
##graph plots
#genomu.nets45 <- tapply(lco.nets45,net.geno45,edge.mean)
#genomu.nets45 <- tapply(inet[net.quad == 'n45.55'],net.geno45,edge.mean)
  genomu.nets45 <- tapply(inet,net.geno,edge.mean)
par(mfrow=c(5,3),mai=c(0.3,0.3,0.3,0.3))
for (i in 1:length(genomu.nets45)){
  v.cex <- v.col<- apply(lco.com[lco$geno == names(genomu.nets45)[i],],2,sum)
  v.col[v.col > 0] <- 'black'
  v.col[v.col == 0] <- 'white'
  v.cex <- log(v.cex+1)
  v.cex <- v.cex + 1
  e.lwd <- (abs(genomu.nets45[[i]])*100)^9
  e.lwd[e.lwd > 25 & e.lwd < 50] <- 15
  e.lwd[e.lwd > 50] <- 25
  gplot(abs(genomu.nets45[[i]]),mode='circle',gmode='graph',vertex.sides=50,vertex.col=v.col,displaylabels=true,vertex.border='black',vertex.cex=v.cex,label.cex=1.25,edge.lwd=e.lwd)
  title(main=names(genomu.nets45)[i],cex=5)
}

@ 

%%%figure for macrobiology grant
<<results=hide,echo=false>>=
  net.figs<- c((1:length(genomu.nets45))[names(genomu.nets45) == '1008'],(1:length(genomu.nets45))[names(genomu.nets45) == '10'],(1:length(genomu.nets45))[names(genomu.nets45) == '11'])
  genomu.nets45. <- genomu.nets45
  for (i in 1:length(genomu.nets45.)){
    colnames(genomu.nets45.[[i]]) <- rownames(genomu.nets45.[[i]]) <- 1:nrow(genomu.nets45.[[i]])
  }
  par(mfrow=c(1,length(net.figs)))
  for (i in net.figs){
    v.cex <- v.col <- apply(lco.com[lco$geno == names(genomu.nets45)[i],],2,sum)
    v.col[v.col > 0] <- 'black'
    v.col[v.col == 0] <- 'white'
    v.cex <- log(v.cex+1)
    v.cex <- v.cex + 1
    if (names(genomu.nets45)[i] == '11'){v.cex[names(v.cex) == 'xmon'] <- 1;v.col[names(v.cex) == 'xmon'] <- 'black'}
    e.lwd <- (abs(genomu.nets45[[i]])*100)^9
    e.lwd[e.lwd > 25 & e.lwd < 50] <- 15
    e.lwd[e.lwd > 50] <- 25
#    gplot(abs(genomu.nets45.[[i]]),gmode='graph',vertex.sides=50,vertex.col=v.col,displaylabels=true,vertex.border='black',vertex.cex=v.cex,label.cex=1,edge.lwd=e.lwd)
    gplot(abs(genomu.nets45.[[i]]),mode='circle',gmode='graph',vertex.sides=50,vertex.col=v.col,displaylabels=true,vertex.border='black',vertex.cex=v.cex,label.cex=1,edge.lwd=e.lwd)
    title(main=paste('genotype',names(genomu.nets45.)[i],sep=''),cex=10)
  }

@ 


%%%chunk11
<<echo=false,results=hide,label=ordinet,include=false>>=
  ##ordination of network statistics
                                        #the whole network
#pc.45 <- princomp(net.dist45)
net.s <- lapply(inet,function(x) length(apply(x,2,bin.sum)[apply(x,2,bin.sum) != 0]))
net.l <- lapply(inet,function(x) length(x[x != 0]))
net.c <- unlist(lapply(inet,function(x) centralization(x,degree,mode='undirected')))
net.n2 <- lapply(lco.com.all,function(x) length(apply(x,2,bin.sum)[apply(x,2,bin.sum) == 2]))

pc.45 <- princomp(inet.dist)
env.45 <- cbind(net.rough,net.rich,net.s,net.l,net.c,net.n2)
ord.45 <- pc.45$scores[,1:2]
colnames(env.45) <- c('roughness','richness','size','links','centrality','doubles')
vfit45 <- envfit(ord.45,env.45)

ord.mu45 <- cbind(tapply(ord.45[,1],net.geno,mean),tapply(ord.45[,2],net.geno,mean))
ord.se45 <- cbind(tapply(ord.45[,1],net.geno,function(x) sd(x)/sqrt(length(x))),tapply(ord.45[,2],net.geno,function(x) sd(x)/sqrt(length(x))))
ord.sd45 <- cbind(tapply(ord.45[,1],net.geno,sd),tapply(ord.45[,2],net.geno,sd))
ord.ciu45 <- ord.mu45 + ord.se45
ord.cil45 <- ord.mu45 - ord.se45

plot(ord.mu45,col=rainbow(max(as.numeric(factor(rownames(ord.mu45)))))[as.numeric(factor(rownames(ord.mu45)))],cex=2,xlim=c(min(ord.cil45[,1]),max(ord.ciu45)),ylim=c(min(ord.cil45[,2]),max(ord.ciu45[,2])),pch=as.numeric(factor(rownames(ord.mu45))),xlab='pc1',ylab='pc2')

for (i in 1:nrow(ord.mu45)){
  lines(c(ord.mu45[i,1],ord.mu45[i,1]),c(ord.cil45[i,2],ord.ciu45[i,2]),col=grey(0.25)[1])
  lines(c(ord.cil45[i,1],ord.ciu45[i,1]),c(ord.mu45[i,2],ord.mu45[i,2]),col=grey(0.25)[1])
}

plot(vfit45,col='black',lwd=5)
legend('bottomright',legend=rownames(ord.mu45),pch=as.numeric(factor(rownames(ord.mu45))),col=rainbow(max(as.numeric(factor(rownames(ord.mu45)))))[as.numeric(factor(rownames(ord.mu45)))],bg='white',border='grey',cex=0.65)

#plot(pc.45,las=2)
#plot(pc.45$scores[,1:2],col=rainbow(max(as.numeric(factor(net.geno45))))[as.numeric(factor(net.geno45))],pch=19,cex=2)

@ 


%%%chunk11
<<echo=false,results=hide,label=ordinet,include=false>>=
  ##ordination of network statistics
#pc.45 <- princomp(net.dist45)
pc.45 <- princomp(inet.d45)
env.45 <- cbind(net.s45,net.l45,net.rich45,net.c45,net.rough45)
ord.45 <- pc.45$scores[,1:2]
colnames(env.45) <- c('size','degree','richness','centralization','roughness')
vfit45 <- envfit(ord.45,env.45)

ord.mu45 <- cbind(tapply(ord.45[,1],net.geno45,mean),tapply(ord.45[,2],net.geno45,mean))
ord.se45 <- cbind(tapply(ord.45[,1],net.geno45,function(x) sd(x)/sqrt(length(x))),tapply(ord.45[,2],net.geno45,function(x) sd(x)/sqrt(length(x))))
ord.sd45 <- cbind(tapply(ord.45[,1],net.geno45,sd),tapply(ord.45[,2],net.geno45,sd))
ord.ciu45 <- ord.mu45 + ord.se45
ord.cil45 <- ord.mu45 - ord.se45

plot(ord.mu45,col=rainbow(max(as.numeric(factor(rownames(ord.mu45)))))[as.numeric(factor(rownames(ord.mu45)))],cex=2,xlim=c(min(ord.cil45[,1]),max(ord.ciu45)),ylim=c(min(ord.cil45[,2]),max(ord.ciu45[,2])),pch=as.numeric(factor(rownames(ord.mu45))),xlab='pc1',ylab='pc2')

for (i in 1:nrow(ord.mu45)){
  lines(c(ord.mu45[i,1],ord.mu45[i,1]),c(ord.cil45[i,2],ord.ciu45[i,2]),col=grey(0.25)[1])
  lines(c(ord.cil45[i,1],ord.ciu45[i,1]),c(ord.mu45[i,2],ord.mu45[i,2]),col=grey(0.25)[1])
}

plot(vfit45,col='black',lwd=5)
legend('bottomright',legend=rownames(ord.mu45),pch=as.numeric(factor(rownames(ord.mu45))),col=rainbow(max(as.numeric(factor(rownames(ord.mu45)))))[as.numeric(factor(rownames(ord.mu45)))],bg='white',border='grey',cex=0.65)

#plot(pc.45,las=2)
#plot(pc.45$scores[,1:2],col=rainbow(max(as.numeric(factor(net.geno45))))[as.numeric(factor(net.geno45))],pch=19,cex=2)

@ 

%%%chunk12
<<echo=false,results=hide,label=pairsplot,include=false>>=
  p.plot <- cbind(net.rich45,net.s45,net.l45,net.c45)
colnames(p.plot) <- c('richness','size','degree','centralization')
pairs(p.plot,cex=0.85,upper.panel=panel.lm,lower.panel=panel.cor)

@ 

\textbf{take-home:} foundation species genetics influences the structure of
  interactions among bark lichen species most likely by altering the
  trajectory of community assembly.

\section{abstract}
\begin{itemize}
\item understanding the complexities of community dynamics requires a
  greater understanding of the interactions among species and the
  forces that influence the structure of these interactions. 
\item we present a study of bark lichen communities associated with
  \textit{populus angustifolia} (narrowleaf cottonwood), where we
  applied quantitative network modeling to investigate the genetic
  effects of a foundation tree species on bark-lichen community
  interactions networks.
\item there were three main findings:
  \begin{enumerate}
  \item genotype significantly predicted the similarity of lichen
    interactions networks. species richness explained additional
    variation in network similarity.
  \item both genotype and richness significantly predicted the
    variation in three network structural metrics (size, degree and
    centralization). 
  \item all network metrics were highly correlated with each other and
    lichen species richness. thus, after controlling for the variation explained by lichen
    species richness, all three network metrics significantly
    predicted variation in the similarity of networks but only
    network size explained a biologically relevant amount of variation
    in network similarity. 
  \end{enumerate}
\item these results strongly support the hypothesis that there is a
  genetic component to the structure of species interactions. our
  quantative network modeling and network analyses show that this
  genetic effect is not due to variation in lichen species richness
  arising from genotype, but by some other causal pathway. these
  results indicate that the variation in network structure among
  genotypes arises from the communities being at different levels of
  community assembly, as both species richness and the size of the
  network independently explained the most variation in network similarity.
\item these findings are particularly important as they suggest that
  quantitative modeling of community-wide interaction networks can aid
  our understanding of community dynamics and that we need to place
  interactions among species within an evolutionary framework.
\end{itemize}

\section{introduction}
\begin{itemize}
\item understanding complex species interactions is important for
  ecology (reviewed in bascompte 2009, and others...). 
\item a substantial body of evidence provides support for the value in
  putting communities and ecosystems into an evolutionary framework
  (reviewed in prs-b 2011, johnson and agrawal 200?, whitham et
  al. 2008 and whitham et al. 2007). however, there is still little
  known about how genetic variation in a foundation species affects
  the interactions among multiple species in complex communities (but
  see bailey et al 2005).
\item defining species interactions and obtaining quantitative data
  for interactions in complex communities presents a challenge to
  ecologists.
\item newly developed quantitative network modeling methods provide
  one means to not only obtain estimates of species interactions but
  also circumvent the need to limit interactions to one or few
  categories (e.g. trophic, mutualistic or host-parasite
  interactions).
\item here, we present the results of a study of how foundation
  species genetics influences variation in interactions among multiple
  species.
\end{itemize}

\section{methods}
\begin{itemize}
\item garden description. 
\item samling description. the presence of bark lichen species were
  assessed within 50 replicate 1 cm$^2$ grid cells of 10 cm$^2$
  quadrats on replicate clones of known genotype in a  common garden
  at the ogden nature center (utah, usa). 50 out of the  100 cells in
  each quadrat were sampled in a checker-board pattern in  order to
  minimize the probability of individuals overlapping between
  cells. 122 trees sampled, 13 genotypes, 5800 grid cells.
\item network modeling. network models were generated using a
  correlation based algorithm to detect species interactions on each
  individual tree. thus, we produced a quantitative, undirected model
  of species interactions on each individual tree.
\item statistical methods for network similarity. we then applied
  network analyses and mutlivariate statistical methods to test for
  the effect of genotype on lichen community interaction network
  structure. in order to compare networks, we measured the similarity
  between networks as the sum of the euclidean distance for all edges
  between each network pair for all networks. this formed a distance
  matrix that we then used in permanova analyses of the factors
  influencing network similarity. we used anova to analyze the effect
  of genotype and richness on the network structural metrics. to
  visualize the similarity of network genotypes, we applied prinicipal
  components analysis to the network distances and used ordination
  vector fitting methods to explore the possible sources of similarity
  among netowrks. 
\end{itemize}

\section{results}

\begin{enumerate}
\item we found significant variation in network structure among tree
  genotypes (fig. 1). genotype and lichen species richness were both
  significant predictors of the structural similarity of the lichen community networks with genotype
  and richness explaining
  \sexpr{round(unlist(adonis.genoxrich$aov.tab)[21],2)*100}\% and
  \sexpr{round(unlist(adonis.genoxrich$aov.tab)[22],2)*100}\% of the
  variation in lichen network similarity (table 1). 
\item we investigated several network statistics to explore the
  structural variation responsible for the variation in network
  similarity and found that genotype and richness significantly
  predicted the variation in all three network metrics (fig. 2 and
  tables 2-4). note that bark roughness was not a significant
  predictor of network similarity ($p = $ \sexpr{vfit45$'vectors'$'pvals'[5]}).
\item  all network metrics were highly correlated with each other and
  lichen species richness (fig. 3). thus, after controlling for the variation explained by lichen
  species richness, all three network metrics significantly
  predicted variation in the similarity of networks but only
  network size explained a biologically relevant amount of variation
  in network similarity.  ($r^2 = $
  \sexpr{round(unlist(adonis.netd.all$aov.tab)[26],2)}) after
  controlling for the variation explained by lichen species richness
  (table 5).
\end{enumerate}


\section{conclusion}

\begin{itemize}
\item genotype influences the size, degree and centralization of
  lichen community interaction networks. it is important to note
  that none of these network metrics were significantly predicted by
  the number of trees sampled for a given genotype (i.e. variation in
  the number of observations did not produce these patterns). 
\item this pattern does not seem to be related to the bark roughness,
  as richness and community composition seem to be. this is
  intriguing since roughness seems to be an important
  factor in lichen establishment and a good predictor of the genotype
  effect on the distribution of the dominant lichen species (lamit et
  al. 2010).
\item these results are particularly striking given that lichen
  species are very slow growing and that our communities are all
  likely to be in the early stages of establishment.
\item these findings are important as they present a
  step toward putting complex, community-wide
  interactions in an evolutionary framework.
\end{itemize}


\pagebreak

%table 1. permanova table for genotype x richness model
%%%chunk13
\begin{center} 
<<echo=false,results=tex,fig=false>>=
  xtable(adonis.genoxrich$aov.tab,caption='anova table for the permanova test of the effect of genotype and lichen species richness on the similarity of the lichen interaction networks.')
@ 
\end{center} 

\pagebreak

%table 2-4. anova tables for the effect of genotype and richness on the
%structural statistics.
%%%chunk14
\begin{center} 
<<echo=false,results=tex,fig=false>>=
  xtable(aov.s45.genoxrich,caption='anova table for the tests of the effects of genotype and richness on network size (i.e. the number of species in the network).')
@ 
\end{center} 

%%%chunk15
\begin{center} 
<<echo=false,results=tex,fig=false>>=
  xtable(aov.l45.genoxrich,caption='anova table for the tests of the effects of genotype and richness on network degree (i.e. the number of connections).')
@ 
\end{center} 

%%%chunk16
\begin{center} 
<<echo=false,results=tex,fig=false>>=
  xtable(aov.c45.genoxrich,caption='anova table for the tests of the effects of genotype and richness on network centralization (i.e. the degree to which the network is dominated by one species).')
@ 
\end{center} 

\pagebreak

%table 3. permanova of the effect of the three metrics after removing
%the variance explained by richness.
%%%chunk17
\begin{center} 
<<echo=false,results=tex,fig=false>>=
  xtable(adonis.netd.all$aov.tab,caption='anova table for the permanova test of the effects of the network metrics (size, degree and centralization) on network similarity after removing the variance explained by richness.')
@ 
\end{center} 

\pagebreak

%figure 1 is the mean network graphs for each genotype.
%%%chunk18
\begin{figure} 
\begin{center} 
<<label=gplots,fig=true,echo=false,width=13,height=20>>=
<<gplots>> 
@ 
\end{center} 
\caption{network graphs for each genotype. points represent species scaled by
the log of there total frequency of occurrence and lines show the
means of significant connections between species across genotype
replicates scaled by their magnitudes. species points that had zero
frequencies are colored white.}

\label{fig:one}
\end{figure}


%figure 2 is the ordination plot with the vectors.
%%%chunk19

\begin{figure} 
\begin{center} 
<<label=ordinet,fig=true,echo=false>>=
<<ordinet>> 
@ 
\end{center} 
\caption{principle components ordination plot of the similarity
  between networks. points represent the genotype means for the
  ordinated scores and bars show the spread (1 s.e.). vectors show the
strength (vector length) and the direction of spread networks (vector
direction) of the correlation between roughness, the network metrics
(size, degree and centralization) and richness and the ordinated
networks.}
\label{fig:two}
\end{figure}


%figure 3 is the pairs plot of the relationship between richness and
%the three network structural variables.
%%%chunk20
\begin{figure} 
\begin{center} 
<<label=pairsplot,fig=true,echo=false>>=
<<pairsplot>> 
@ 
\end{center} 
\caption{matrix of bivariate plots for the network structure
  statistics (size = number of species in the network, degree = number
of connections and centralization = dominance of the network by one
species) and species richness (measured as the number of species
present in the quadrat). note that although a species may have been
present in a quadrat, it may not have a significant connection to
any other species in the community.}
\label{fig:three}
\end{figure}


%%%pit
<<>>=


@ 


