\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{Arthropod Coocurrence Study}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle

\textbf{Tasks}
\begin{itemize}
\item Test for number of senescing leaves correlation with Pb
\item Think about direct versus indirect genetic effects on community
\item Test genotype effect on all species
\item Get genetic distance data (RFLP?), maybe ask Zaccheus
\item Think about genetic basis of leaf abscision/senescence
\end{itemize}

\section{30 Jan 2014}

Continuing to work on script.

Results Summary

\begin{itemize}
\item PB effects: 
  \begin{itemize}
  \item PB (as percent) decreased from senescent to live leaves
    (Paired t=-5.58,df=34,P=0.000003)
  \item Genotype did not affect the change in PB as percent (REML:ch2=2.81,P=0.094)
  \item Genotype affects (pb=liv+sen) (REML:chi2=4.20,P=0.040,df=1) 
  \item Genotype affects liv (REML: chi2=6.75,P=0.009) but not sen
    (REML: chi2=3.32,P=0.068) using percent abundances
  \end{itemize}
\item Composition
  \begin{itemize}
  \item Liv and Sen leaves were compositionally different (relativized)
    (Multivariate Paired distance based t-test: t=23.74,df=34,P=2.2e-16)
  \item Genotype did not affect the difference in composition between
    live and sen (REML: chi2=0.53,P=0.465)
  \item Genotype and tree type influenced community composition but
    did not interact (PERM:
    dfgeno=6,F=1.96,P=0.004,R2=0.14,dfleaf=1,F=10.71,P=0.001,R2=0.12,dfint=6,F=1.31,R2=0.09,P=0.125)
  \end{itemize}
\item Co-occurrence patterns
  \begin{itemize}
  \item Both live and sen show similar tree total co-occurrence
    patterns (SESlive=-6.85,P=0.001,SESsen=-5.87,P=0.001)
  \item Sen and Liv show different patterns of co-occurrence
  \item Do a paired analysis
  \end{itemize}
\item Nestedness
  \item R1 nestedness is only significant for Live leaves
  \item R00 and R0 nestedness are significant for both
  \item C0 nestedness is only signficant for Sen leaves
\end{itemize}

\section{29 Jan 2014}

Analyze data for the following:

- Genetic effect on P. betae \\
- Genetic effect on composition \\
- Genetic effect on SES \\
- Co-occurrence network structure \\
- Nestedness for live and senesced \\


\section{4 Dec 2013}
Notes from meeting with Tom:

\begin{itemize}
\item P. betae phenology likely done by late June (see Williams and Whitham)
\item Test for number of senescing leaves correlation with Pb
\item Think about direct versus indirect genetic effects on community
\item Test genotype effect on all species
\item Get genetic distance data (RFLP?), maybe ask Zaccheus
\item Think about genetic basis of leaf abscision/senescence
\end{itemize}

\section{2 Dec 2013}

Results of analysis of liv and sen
\begin{itemize}
\item Networks are sparse but show distinct differences, need to
  figure out how to compare models
\item Co-occurrence
%%%Arthropods only

%%%Arthropods and Fungi
\item Co-occurrence increases after senescence (t = 2.1951, df = 30, p-value = 0.03603)
\item Genotype effect live: geno.ses     6  22.46   3.743   1.006  0.441
\item Genotype effect sen: geno.ses     6  33.59   5.599   4.699
  0.002 **geno.ses     6  33.59   5.599   4.699  0.002 **
\item Genotype mean ses shift from some positive to all negative going
  from sen to liv

\item Greater percent pemphigus on sen than live (t = 5.4687, df = 34, p-value = 4.226e-06)
\item No difference in fungus (t = -1.8687, df = 34, p-value = 0.07031)
\end{itemize}

\textbf{Dataset Alterations}
\begin{enumerate}
\item Check the following
  \begin{enumerate}
  \item np5.5 doesn't exist but "NP6-5  1023       1   M"
  \item np13.10 1017_live - "235 NP13-10  1017       1   M"
  \item np2.4 1023_live - "199 NP2-4 1000C       0   F"
  \item "np3.36 1000_live"  "np3.36 11_sen" - "168 NP3-36  1000       0   F"
  \item np4.23 1023_sen - "147 NP4-23  1023       1   M"
  \end{enumerate}
\item np5.5 does not exist in the pit dataset, changing to np6.5
\item np3.36 is genotype 1000, changing in dataset from 11 to 1000 for sen
\item np2.4 is 1000, but there is no np2.4 in the senescing dataset,
  make np2.4 into np4.23.
\item np13.10 missing in senescing dataset, make np13.10 sen zero.
\item All passed the following test:
\begin{verbatim}
    all(sort(unique(paste(test[[1]]$geno,test[[1]]$tree)))==sort(unique(paste(test[[2]]$geno,test[[2]]$tree))))
\end{verbatim}
\end{enumerate}

Notes from samples:

\begin{itemize}
\item NP2-10 996 tree: almost all leaves from one branch, which
  appeared to be dying back.
\item NP8.22 T6 tree: "weird"
\item NP6.05 1023 tree: check tree number. Could be NP5.05.
\item np2.21 1000 tree: pair of green leaves with galls and leaf tier
\item np4.23 1023 tree: should it be np4.27?
\item np5.25 996 tree: yellow leaf with gall tied to one green leaf
  (no gall), which fell apart
\item np3.12 1000 tree: fungal branch infection on most branches. Most
  leaves from 3 branches
\item np3.36 11 tree: 1000? check litter and garden info
\end{itemize}

\section{26 Nov 2013}



\section{15 Nov 2013}
\begin{itemize}
\item Wait to process litter leaves, they are mixed with other leaves
  and would need to be sorted
\item Moving them into Bio340
\item Transporting senescing leaves back to Cambridge
\end{itemize}

\section{11 Nov 2013}

\begin{itemize}
\item Group woodies with non-woody
\item How do you handle the absence of senescent leaves?
\item What about the affect of Pemphigus loads on individual leaves or
  on trees?
\end{itemize}

\textbf{Senescent Leaf Data Collection Notes}

\begin{itemize}
\item Double check and correct np3.36 genotype from Master Sheet
\item Pb.upper = gall opening is on the upper side of the leaf
\item Fungal = necrotic tissue
\item Think about fungal from previous observations, maybe just call
  it necrosis
\end{itemize}

\section{7 Nov 2013}

\begin{itemize}
\item Running genotype sensitivity analysis
\item Not significantly different when removing just one genotype
\item Try removing more genotypes
\end{itemize}

\section{6 Nov 2013}

\begin{enumerate}
\item Decide on species groups 
\item Re-run analyses
\item Collect senescing and leaf litter data
\item Identify to species using Randy's notebook
\item Look into Gina's time paper
\item Serphid and Chanamyid flies

\end{enumerate}

\section{5 Nov 2013}

Running preliminary analyses.
\begin{enumerate}
\item Stand level networks (structure)
\item Tree level co-occurrence patterns (significant genotype effect)
\end{enumerate}


\section{Before 15 Oct 2013}

\subsection{Tasks}
\begin{itemize}
\item Photograph representatives of all leaf mods
\item Measure average specific leaf area for each shoot
\item Weigh leaf mods where possible
\item Run co-occurrence analyses on leaf modifiers
\item Run analysis of genotypic effect on leaf mod co-occurrence
  patterns
\item Add covariates to genetic model
\end{itemize}


\textbf{Process Summary}
\begin{itemize}
\item ONC Co-Occurrence 2012
  \subitem Did a preliminary analysis of the co-occurrence data with
  tree level co-occurrence patterns among genotypes
  \subitem Significant genotype pattern of observed C-scores
  \subitem Average dp networks "look" different
  \subitem Can still average among shoots prior to analysis
  \subitem Need to check effects of the number of leaves sampled
\item Art's 2004-2006 data
\item Gina's 2002-2003 data
\end{itemize}


\textbf{Summary}

\begin{itemize}
\item Study the cooccurrence patterns of leaf modifying arthropods on
  different genotypes of Narrowleaf Cottonwood (\texit{Populus angustifolia}).

\end{itemize}

\subsection{Meta-data}
\begin{itemize}
\item Leaves collected from trees of known genotype in the north
  garden of the Ogden Nature Center on 4 May 2012.
\item Between 3 and 4 branches were cut from 15-20 feet on the west
  aspect of trees.
\item Branches were stored in water until the leaf shoots were removed
  from each branch.
\item Branches were between 0.5 and 1 cm in diameter
\item Small (~0.25 cm) green leafhoppers abundant
\item Leaves were stored in ziplock bags until processed (~ 1 week)
\item Leaf modifiers were scored at the leaf scale, keeping track of the
  identity of each shoot
\item Small, young/juvenile leaves close to the apical meristem were
  not surveyed, as they would not have equal exposure time to
  arthropods
\item NOTE: N4.30 P. betae tends to be higher up on the leaf above the
  junction of the leaf and the petiole
\item NOTE: In future studies, you can write the shoot number on the
  leaves, and possibly the leaf number
\item NOTE: Specimen N2-9 had many instances of some kind of black rot
  in the petioles that almost always coincided with pemphigus galls
  and sometime phylocolpa. It also occurred in petioles of adjacent
  stems without pemphigus when there was a high enough load. It seemed
  to grow both out of the gall and up from the stem into the
  petiole. Possibly an effect of nutrient dynamics? 
\end{itemize}


\subsection{PIT Tree Level Co-occurrence Data Aug 2012}

\subsection{Methods}
\begin{enumerate}
\item 20 shoots collected from between 2 and 3 meters height
\item leaves were collected haphazardly from around the entire tree
\item shaded leaves were avoided
\item abscising leaves were avoided
\item 5 leaves per shoot (n=10) for each tree starting from the bottom of the whorl at the first full sized leaf
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%Leaf Modifier Descriptions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item The following leaf modifiers were assessed:
  \begin{itemize}
  \item p.upper (number): Pemphigus opening on upper side of leaf
  \item p.lower (number): Pemphigus opening on lower side
  \item p.nec (number): Pemphigus with necrosis
  \item p.hole (number): Pemphigus with chow hole
  \item p.woody (number): woody Pemphigus gall (likely a different
    species, check senescent leaves for opening location)
  \item p.open (number): Pemphigus that has been opened
  \item chew.edge (presence): chewing at the edge
  \item chew.holes (presence): chewing holes not at edge
  \item lace (presence): lacey chewing
  \item fish.eye (presence): hole with necrosis surrounding
  \item tip.miner (presence): mining at the tip
  \item edge.miner (presence): mining at the edge
  \item fungal (presence): fungal necrosis
  \item chomp (presence): large removal of tissue
  \item pinch (presence): pinching at the edge of the leaf
  \item thirps (presence): thrip damage (golden-brown hue with exuvia and frass)
  \end{itemize}
\end{enumerate}



%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


