\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{/Library/Frameworks/R.framework/Resources/share/texmf/Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{Evolution on Ecological Networks}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle

\thispagestyle{empty}

\setcounter{tocdepth}{3}  %%activate to number sections
\tableofcontents

\section{23 Jan 2014}
Working on the final EEN analyses:

\begin{enumerate}
\item Simulate networks with varying levels of genotypic effects and a
  percent genetic variance equivalent to published community
  heritability estimates
\item In an appendix, develop the use of permanova R2, inlcuding:
  \begin{enumerate}
  \item Calculation using Anderson's method
  \item Comparison to NMDS method in Shuster 2006
  \end{enumerate}
\item Measure nestedness and examine correlation between genetic
  variance and nestedness
\item Conduct Removal experiments (random vs targeted removal):
  \begin{enumerate}
  \item Random removal
  \item Genotype removal based on phenotpic similarity
  \item Centralized species removal
  \end{enumerate}
\end{enumerate}

Coding in source file, een.R. 

\section{22 Jan 2014}

Re-organized the flow for community simulation with cgSim.

Added two new functions to support cgSim: simTrees and simSpp.

Compared output (gamma and H2C) with Shuster 2006 output. Everything
checks out with the exception of NMDS rotation error and slight
numerical differences in H2C.

\section{14 Jan 2014}

Does genetic variation contribute to nestedness in ecological networks?

<<>>=
library(ComGenR)
  ##Types of trait distribution
  ##uniform/random
tree.trait <- runif(100,10,20)
arth.trait <- rnorm(100,15,1)
S <- tree.trait - arth.trait
hist(S)
plot(tree.trait,arth.trait)
  ##increasing

  ##decreasing
  ##convex (bowl down)
tree.trait <- rnorm(100,15,1)
arth.trait <- rnorm(100,15,1)
S <- tree.trait - arth.trait
par(mfrow=c(1,2))
hist(S)
plot(tree.trait,arth.trait)
  ##concave (bowl up)

###Run a set of simulations across a gradient of increasing genotype variation and measure nestedness

##Increase the range for a uniform distribution
c.r <- 15.5 #center of the range
ns.r <- 15 #number of steps over the range
ng.r <- 10 #number of genotypes over the range
nr.g <- 5 #number of reps for each genotype
s.r <- 0.5 #step size over range
steps <- seq(0,ns.r*s.r,by=s.r)
tp.l <- list()
for (i in 1:ns.r){
  tp.l[[i]] <- gpmTrees(seq((c.r-steps[[i]]),(c.r+steps[[i]]),length=ng.r),nr.g)
}
cp.l <- gpmCom(n=20)
com.sim <- lapply(tp.l,function(x) cgSim(tree.pheno=x,insect=cp.l,YY=1,GG=8,reps=1))
com.sim. <- list()
for (i in 1:length(com.sim)){
  com.sim.[[i]] <- round(com.sim[[i]][[1]][[1]][[8]],0)
}
com.nest <- unlist(lapply(com.sim.,function(x) nestedtemp(x)$statistic))
V.g <- unlist(lapply(tp.l,function(x) var(x[,2])))
                                        #Correlation between H2Cnms~Vg and H2Cperm~Vg
cs.nms1d <- list()
cs.stress <- list()
for (i in 1:length(com.sim.)){
  cs.nms1d[[i]] <- nmds(vegdist(com.sim.[[i]]),1,1)
  cs.stress[[i]] <- min(cs.nms1d[[i]]$stress)
  cs.nms1d[[i]] <- nmds.min(cs.nms1d[[i]])[,1]
}
h2c.nms <- lapply(cs.nms1d,getH2C,g=as.character(tp.l[[1]][,1]))
h2c.nms <- do.call(rbind,h2c.nms)[,2]
h2c.adonis <- pblapply(com.sim.,function(x,g) adonis(x~g),g=as.character(tp.l[[1]][,1]))
h2c.perm <- unlist(lapply(h2c.adonis,function(x) x$aov.tab[1,5]))
summary(lm(h2c.nms~V.g))
summary(lm(h2c.perm~V.g))
plot(h2c.nms~V.g,pch=19,xlab='Vg',ylab='H2C',col='grey',ylim=c(0,0.85),font.lab=2)
points(h2c.perm~V.g,pch=19,col='black')
abline(lm(h2c.nms~V.g),col='grey',lty=2)
abline(lm(h2c.perm~V.g),col='black')
legend('topleft',legend=c('NMDS','PerMANOVA'),col=c('grey','black'),pch=19)
h2c.ancova <- data.frame(vg=c(V.g,V.g),
                         type=c(rep('nms',length(h2c.nms)),rep('perm',length(h2c.perm))),
                         h2c=c(h2c.nms,h2c.perm))
summary(lm(h2c~vg+type,data=h2c.ancova))
                                        #
par(mfrow=c(1,2))
plot(density(tp.l[[1]][,2]),main='',xlab='Tree Phenotype',xlim=c(5,27),ylim=c(0,1),col=0)
for (i in 2:length(tp.l)){lines(density(tp.l[[i]][,2]),col=heat.colors(length(tp.l))[i])}
plot(com.nest~I(V.g/max(V.g)),pch=1,col='grey',cex=1.5)
points(com.nest~I(V.g/max(V.g)),pch=19,col=heat.colors(length(tp.l))[1:length(tp.l)])
abline(lm(com.nest~I(V.g/max(V.g))))
                                        #
par(mfrow=c(1,2))
plotweb(com.sim.[[1]][order(apply(com.sim.[[1]],1,function(x) sum(sign(x))),decreasing=TRUE),
                      order(apply(com.sim.[[1]],2,function(x) sum(sign(x))),decreasing=TRUE)],method='normal')
plotweb(com.sim.[[15]],method='normal')
cgPlotweb <- function(x,g){
  x <- x[order(apply(x,1,function(x) sum(sign(x))),decreasing=TRUE),
           order(apply(x,2,function(x) sum(sign(x))),decreasing=TRUE)]
  plotweb(apply(x,2,function(x,g) tapply(x,g,mean),g=g),method='normal')
}
cgImage <- function(x,xlab='',ylab='',col=c(0,1)){
  x <- x[order(apply(x,1,function(x) sum(sign(x))),decreasing=TRUE),
         order(apply(x,2,function(x) sum(sign(x))),decreasing=TRUE)]
  x[x!=0] <- 1
  image(t(x),col=col,xaxt='n',yaxt='n')
  mtext(side=c(1,2),c(xlab,ylab),font=2)
}

par(mfrow=c(1,2))
cgPlotweb(com.sim.[[1]],tp.l[[1]][,1])
cgPlotweb(com.sim.[[15]],tp.l[[15]][,1])
cgImage(com.sim.[[1]],xlab='Tree Genotype',ylab='Insect Species',col=c(0,'grey'))
cgImage(com.sim.[[15]],xlab='Tree Genotype',ylab='Insect Species',col=c(0,'grey'))

@ 

\section{9 Jan 2014}
Developing the manuscript, package and vignette for lab meeting. 

Package
\begin{enumerate}
\item Debug current set of functions
\item Populate help files
\item Check --as-cran
\item Build as v1.0
\item Post to github
\item Post to cran
\end{enumerate}

Vignette
\begin{enumerate}
\item Write body text
\item Set figures
\item Proof
\end{enumerate}

Manuscript
\begin{enumerate}
\item Two articles 1) Methods in Ecology and Evolution = Vignette and 2)
  Ecography = Modeling and Data
\item Summarize results
\item Write outline
\end{enumerate}


\section{7 Jan 2014}

<<>>=
###Moved to src/een_sim.R

@ 

\section{20 Dec 2013}
Add data from Gina, Art, Rikke and Cam, Adrian?

The idea being to simulate but then observe patterns in real data.

\section{18 Dec 2013}
Sent outline (see Docs) to Steve. Check back with him in a couple of
days. 


\section{17 Dec 2013}

\begin{enumerate}
\item Conducting network modeling
\end{enumerate}

\section{16 Dec 2013}

Results
\begin{itemize}
\item Lonsdorf model produces nested biparite genotype-species networks at high
  levels of genetic effects
\item Lonsdorf model also produces co-occurrence network structure at
  high levels of genetic effects
\end{itemize}

Look at Jelle's models of stability.

Check Lonsdorf's model output with your R cod output.

Analyze the simulation output from two perspectives: 1) bipartaite
network structure of tree species and 2) co-occurrence patterns in
dependent communities. 

From the bipartite perspective, if we assume nestedness, how will
networks evolve.

From the co-occurrence perspective, what network patterns arise given
different amounts of influence of genetics versus environment. The
interaction context comes in the form of co-occurrences influencing
encounter rates, which are the rate limiting step for interactions.

Also from both of these perspectives, keep in mind the possibility of
actually looking at interactions among species. 

Notes on Lonsdorf Code
\begin{itemize}
\item Line 30 "art_r" doesn't match any other variables in the code,
  most likely a typo and shoulg be art_g
\item 
\end{itemize}


\section{11 Dec 2013}

Strategy for Chap3
\begin{verbatim}
- seeNets package on CRAN
- seeNets pub MEE
* Make sure to email Araujo et al.
- add simulator, which will show the development of networks along a
genetic gradient
* This can be based on the Shuster 2006 paper so that you don't scoop
the Lonsdorf manuscript
\end{verbatim}

\section{6 Dec 2013}

What does the co.net tell us?
Significant co-occurrences in units of standard deviations by default.

What does the dep.net tell us?
Significant conditional probability of co-occurrence of one species
given another. Conditional probability is the co-occurrence
probability divided by the occurrence probability of one species.

Apply network modeling to Lonsdorf output:

<<>>=
source('../src/lonsdorf.R')
source('../../lichen_coo/src/seenetR.R')
library(sna)
x <- lapply(out[[1]][[4]],round,digits=0)
for (i in 1:length(x)){
  x[[i]][x[[i]]<10] <- 0
}
con <- lapply(x,co.net)
par(mfrow=c(1,2))
coord <- gplot(abs(con[[1]]))
gplot(abs(con[[8]]),coord=coord)


@ 

\section{26 Nov 2013}


Need to review species interaction network literature, focusing on
simulations:

\begin{itemize}
\item Baiser's metabolic network
\item Allesina's networks
\item Sala's networks
\end{itemize}


\section{Before 26 Nov 2013}

\subsection*{Outline}
\begin{itemize}
\item Main Question: how does the structure of ecological networks
  influence the evolution of species in the community?
\item Simulate the evolution of traits determining interactions (and
  possibly linked traits of varying association)
\item Review:
  \begin{itemize}
  \item Salas manuscript
    \subitem -- Different from Sala's in that it will explore more
    network structure, including modularity
  \item Lonsdorf Manuscript
    \subitem -- Different from Lonsdorf's in that the emphasis is
    exploring how network structure influences evolution
  \item Shuster et al. (2006)
  \item Nuismer and Doebeli (2004)
  \item Nowak 2006 Chapter 8 (population genetics on graphs)
  \end{itemize}
\item Model:
  \begin{itemize}
  \item Individual Based
  \item Genetics -> binary vector
  \item Phenotype -> vector of continuous trait values (\sim N($\mu$,$\sigma$))
  \item Interaction Network -> adjacency matrix + trait matching
  \item Community Dynamics -> demographics (birth - death) and stability
  \item Ecosystem Dynamics -> productivity and energy flow
  \item Evolution -> selection (fitness + reproduction) and
    recombination + mutation
  \end{itemize}
\item Pseudocode:
  \begin{enumerate}
  \item Generate interaction network
    \subitem -- adjacency matrix
    \subitem -- make sure to control for covarying structural
    properties, such as connectence
  \item Generate genome (i.e. create a binary vector)
  \item Map genotype to phenotype (i.e. for each allele draw a value
    (0 <= value < infinity) from a normal distribution)
    \subitem -- Repeat for n individuals in k species
  \item 
  \end{enumerate}
\item Explore:
  \begin{itemize}
  \item Stability - resistance and resilience 
  \item Additive versus non-additive (epistatic) genetic effects
  \item Random, foundation, nested/modular
  \item \textit{Spatial (e.g. relative abundance effects)}
  \item Others...?
  \end{itemize}
\end{itemize}

\section{Check out simecol}
\url{http://cran.r-project.org/web/packages/simecol/vignettes/a-simecol-introduction.pdf}

<<>>=
library(simecol)
?simecol
?indbasedModel

@ 

\section{The Model}

\subsection{Generate Interaction Network}

<<>>=
                                        #generate a square, symmetric adjacency matrix 
rnet <- function(n){
x <- array(sample(c(0,1),(n^2),replace=TRUE),dim=c(n,n))
x[lower.tri(x)] <- t(x)[lower.tri(x)]
return(x)
}
                                        #

@ 

\subsection{Generate Genome}
<<>>=
                                        #generate a genome (binary) of length n
rgenome <- function(n){
  return(sample(c(0,1),n,replace=TRUE))
}
                                        #generate a population of genomes of length n
genomePop <- function(n){
g <- sapply(rep(n,10),function(x) rgenome(x))
g <- split(g, rep(1:ncol(g), each = nrow(g)))
return(g)
}
                                        #generate a community of genomes
                                        #generate a community
                                        #nk is a list of population sizes nk <- split(nk, rep(1:nrow(nk), each = ncol(nk)))
genomeCom <- function(nk){
  return(lapply(nk,function(x) genomePop(x)))
}


@ 

\subsection{Map Genotype to Phenotype}

<<>>=
                                        #map a genotype to a phenotype
gpMap <- function(g,mu,sigma){
  x <- cbind(g,mu,sigma)
  y <- apply(x,1,function(x) if (x[1] == 0){0}else{rnorm(1,x[2],x[3])})
  return(y)
}

@ 

\subsection{Generate a population for each species}

<<>>=
                                        #generate a population
                                        #g is a list of genotypes
                                        #mu is a vector of population trait means
                                        #sigma is a vector of population trait standard deviations
genPop <- function(g,mu,sigma){
  return(lapply(g,function(x,m,s) gpMap(x,m,s),m=mu,s=sigma))
}


@ 

\section{Test Run}

<<>>=
                                        #generate a population of genotypes for each species
                                        #
nk <- as.matrix(rep(15,25)) #create a kX1 matrix of genome lengths
nk <- split(nk, rep(1:nrow(nk), each = ncol(nk))) #create a genome length list for all k species
meta.genome <- genomeCom(rep(15,15)) #create a population of genomes for each species

                                        #1. initialize a population of genotypes
                                        #2. map genotypes to phenotypes using trait means
                                        #3. calculate trait matching using adjacency matrix
                                        #4. calculate fitness using trait matching
                                        #5. select a proportion for reproduction using fitness
                                        #6. recombine and mutate
                                        #7. select a proportion for death
gn <- 15 #genome length

mu <- runif(n,0,100)
sigma <- rnorm(n,15,3)
gpMap(rgenome(15),mu,sigma)


@ 

%% %%Figure construction
%% <<echo=false,results=hide,label=fig1,include=false>>=
%% @ 


%% %%Figure plotting
%% \begin{figure} 
%% \begin{center} 
%% <<label=fig1,fig=TRUE,echo=false>>=
%% <<fig1>> 
%% @ 
%% \end{center} 
%% \caption{}
%% \label{fig:one}
%% \end{figure}


%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


