\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{Arthropod Coocurrence Study}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle

\section{Before 15 Oct 2013}

\subsection{Tasks}
\begin{itemize}
\item Photograph representatives of all leaf mods
\item Measure average specific leaf area for each shoot
\item Weigh leaf mods where possible
\item Run co-occurrence analyses on leaf modifiers
\item Run analysis of genotypic effect on leaf mod co-occurrence
  patterns
\item Add covariates to genetic model
\end{itemize}


\textbf{Process Summary}
\begin{itemize}
\item ONC Co-Occurrence 2012
  \subitem Did a preliminary analysis of the co-occurrence data with
  tree level co-occurrence patterns among genotypes
  \subitem Significant genotype pattern of observed C-scores
  \subitem Average dp networks "look" different
  \subitem Can still average among shoots prior to analysis
  \subitem Need to check effects of the number of leaves sampled
\item Art's 2004-2006 data
\item Gina's 2002-2003 data
\end{itemize}


\textbf{Summary}

\begin{itemize}
\item Study the cooccurrence patterns of leaf modifying arthropods on
  different genotypes of Narrowleaf Cottonwood (\texit{Populus angustifolia}).

\end{itemize}

\subsection{Meta-data}
\begin{itemize}
\item Leaves collected from trees of known genotype in the north
  garden of the Ogden Nature Center on 4 May 2012.
\item Between 3 and 4 branches were cut from 15-20 feet on the west
  aspect of trees.
\item Branches were stored in water until the leaf shoots were removed
  from each branch.
\item Branches were between 0.5 and 1 cm in diameter
\item Small (~0.25 cm) green leafhoppers abundant
\item Leaves were stored in ziplock bags until processed (~ 1 week)
\item Leaf modifiers were scored at the leaf scale, keeping track of the
  identity of each shoot
\item Small, young/juvenile leaves close to the apical meristem were
  not surveyed, as they would not have equal exposure time to
  arthropods
\item NOTE: N4.30 P. betae tends to be higher up on the leaf above the
  junction of the leaf and the petiole
\item NOTE: In future studies, you can write the shoot number on the
  leaves, and possibly the leaf number
\item NOTE: Specimen N2-9 had many instances of some kind of black rot
  in the petioles that almost always coincided with pemphigus galls
  and sometime phylocolpa. It also occurred in petioles of adjacent
  stems without pemphigus when there was a high enough load. It seemed
  to grow both out of the gall and up from the stem into the
  petiole. Possibly an effect of nutrient dynamics? 
\end{itemize}


\subsection{PIT Tree Level Co-occurrence Data Aug 2012}

\subsection{Methods}
\begin{enumerate}
\item 20 shoots collected from between 2 and 3 meters height
\item leaves were collected haphazardly from around the entire tree
\item shaded leaves were avoided
\item abscising leaves were avoided
\item 5 leaves per shoot (n=10) for each tree starting from the bottom of the whorl at the first full sized leaf
\item The following leaf modifiers were assessed:
  \begin{itemize}
  \item p.upper (number): Pemphigus opening on upper side of leaf
  \item p.lower (number): Pemphigus opening on lower side
  \item p.nec (number): Pemphigus with necrosis
  \item p.hole (number): Pemphigus with chow hole
  \item p.woody (number): woody Pemphigus gall
  \item p.open (number): Pemphigus that has been opened
  \item chew.edge (presence): chewing at the edge
  \item chew.holes (presence): chewing holes not at edge
  \item lace (presence): lacey chewing
  \item fish.eye (presence): hole with necrosis surrounding
  \item tip.miner (presence): mining at the tip
  \item edge.miner (presence): mining at the edge
  \item fungal (presence): fungal necrosis
  \item chomp (presence): large removal of tissue
  \item pinch (presence): pinching at the edge of the leaf
  \item thirps (presence): thrip damage (golden-brown hue with exuvia and frass)
  \end{itemize}
\end{enumerate}



%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


